use std::error::Error;
use std::fs;
use std::path::Path;
use std::process::Command;

use gitserious_app::{
    InitStatus, InitializeProjectError, ProjectConfig, ProjectState, ProjectStateStore,
    RepositoryLocator, initialize_project, resolve_project_lock,
};
use gitserious_fs::{GitRepositoryLocator, ProjectStateError, TomlProjectStateStore};
use tempfile::TempDir;

fn repository() -> Result<TempDir, Box<dyn Error>> {
    let directory = tempfile::tempdir()?;
    let status = Command::new("git")
        .args(["init", "-q"])
        .current_dir(directory.path())
        .status()?;
    if !status.success() {
        return Err(format!("git init failed with {status}").into());
    }
    Ok(directory)
}

fn root(directory: &Path) -> Result<gitserious_app::RepositoryRoot, Box<dyn Error>> {
    Ok(GitRepositoryLocator.locate(directory)?)
}

fn project_paths(directory: &Path) -> (std::path::PathBuf, std::path::PathBuf, std::path::PathBuf) {
    let project = directory.join(".gitserious");
    (
        project.clone(),
        project.join("config.toml"),
        project.join("gitserious.lock"),
    )
}

#[test]
fn absent_state_has_no_filesystem_side_effects() -> Result<(), Box<dyn Error>> {
    let repository = repository()?;
    let (project, _, _) = project_paths(repository.path());

    assert_eq!(
        TomlProjectStateStore.inspect(&root(repository.path())?)?,
        ProjectState::Absent
    );
    assert!(!project.exists());
    Ok(())
}

#[test]
fn initialization_writes_exact_config_and_ordered_lock() -> Result<(), Box<dyn Error>> {
    let repository = repository()?;
    let (project, config, lock) = project_paths(repository.path());
    fs::create_dir(&project)?;
    fs::write(project.join("notes.txt"), "preserve me")?;

    let outcome = initialize_project(
        &GitRepositoryLocator,
        &TomlProjectStateStore,
        repository.path(),
    )?;

    assert_eq!(outcome.status(), InitStatus::Initialized);
    assert_eq!(
        fs::read_to_string(config)?,
        "config-version = 1\nactive-template = \"default\"\n"
    );
    let lock = fs::read_to_string(lock)?;
    assert!(lock.starts_with("# This file is generated by gitserious. Do not edit.\n"));
    assert!(lock.ends_with('\n'));
    assert_eq!(
        lock.matches("[[resolved-template.commit-types]]").count(),
        11
    );
    let mut previous = 0;
    for id in [
        "feat", "fix", "refactor", "perf", "test", "docs", "chore", "build", "ci", "style",
        "revert",
    ] {
        let position = lock[previous..]
            .find(&format!("id = \"{id}\""))
            .ok_or_else(|| format!("missing {id}"))?
            + previous;
        assert!(position >= previous);
        previous = position + 1;
    }
    assert_eq!(
        fs::read_to_string(project.join("notes.txt"))?,
        "preserve me"
    );
    Ok(())
}

#[test]
fn matching_state_is_byte_preserving_and_idempotent() -> Result<(), Box<dyn Error>> {
    let repository = repository()?;
    let (_, config, lock) = project_paths(repository.path());
    initialize_project(
        &GitRepositoryLocator,
        &TomlProjectStateStore,
        repository.path(),
    )?;
    let config_before = fs::read(&config)?;
    let lock_before = fs::read(&lock)?;
    let config_modified = fs::metadata(&config)?.modified()?;
    let lock_modified = fs::metadata(&lock)?.modified()?;

    let outcome = initialize_project(
        &GitRepositoryLocator,
        &TomlProjectStateStore,
        repository.path(),
    )?;

    assert_eq!(outcome.status(), InitStatus::AlreadyInitialized);
    assert_eq!(fs::read(&config)?, config_before);
    assert_eq!(fs::read(&lock)?, lock_before);
    assert_eq!(fs::metadata(&config)?.modified()?, config_modified);
    assert_eq!(fs::metadata(&lock)?.modified()?, lock_modified);
    Ok(())
}

#[test]
fn existing_valid_config_creates_only_a_missing_lock() -> Result<(), Box<dyn Error>> {
    let repository = repository()?;
    let (project, config, lock) = project_paths(repository.path());
    fs::create_dir(&project)?;
    let authored = "config-version = 1\nactive-template = \"default\"\n";
    fs::write(&config, authored)?;

    let outcome = initialize_project(
        &GitRepositoryLocator,
        &TomlProjectStateStore,
        repository.path(),
    )?;

    assert_eq!(outcome.status(), InitStatus::LockCreated);
    assert_eq!(fs::read_to_string(config)?, authored);
    assert!(lock.is_file());
    Ok(())
}

#[test]
fn recognized_stale_lock_is_replaced_without_rewriting_config() -> Result<(), Box<dyn Error>> {
    let repository = repository()?;
    let (_, config, lock) = project_paths(repository.path());
    initialize_project(
        &GitRepositoryLocator,
        &TomlProjectStateStore,
        repository.path(),
    )?;
    let authored = fs::read(&config)?;
    let current = fs::read_to_string(&lock)?;
    let stale = current.replace(
        "config-fingerprint = \"sha256:b",
        "config-fingerprint = \"sha256:a",
    );
    assert_ne!(stale, current);
    fs::write(&lock, stale)?;

    let outcome = initialize_project(
        &GitRepositoryLocator,
        &TomlProjectStateStore,
        repository.path(),
    )?;

    assert_eq!(outcome.status(), InitStatus::LockRefreshed);
    assert_eq!(fs::read(&config)?, authored);
    assert_eq!(fs::read_to_string(lock)?, current);
    Ok(())
}

#[test]
fn malformed_unknown_and_unsupported_config_are_refused() -> Result<(), Box<dyn Error>> {
    for contents in [
        "not toml",
        "config-version = 2\nactive-template = \"default\"\n",
        "config-version = 1\nactive-template = \"default\"\nunknown = true\n",
        "config-version = 1\nactive-template = \"Custom\"\n",
    ] {
        let repository = repository()?;
        let (project, config, _) = project_paths(repository.path());
        fs::create_dir(project)?;
        fs::write(config, contents)?;

        assert!(matches!(
            TomlProjectStateStore.inspect(&root(repository.path())?),
            Err(ProjectStateError::ConfigFormat { .. })
        ));
    }
    Ok(())
}

#[test]
fn malformed_unknown_and_unsupported_lock_are_refused() -> Result<(), Box<dyn Error>> {
    for mutation in ["malformed", "unknown", "unsupported"] {
        let repository = repository()?;
        let (_, _, lock) = project_paths(repository.path());
        initialize_project(
            &GitRepositoryLocator,
            &TomlProjectStateStore,
            repository.path(),
        )?;
        let contents = match mutation {
            "malformed" => String::from("not toml"),
            "unknown" => format!("{}unknown = true\n", fs::read_to_string(&lock)?),
            "unsupported" => {
                fs::read_to_string(&lock)?.replacen("lock-version = 1", "lock-version = 2", 1)
            }
            _ => return Err("unexpected mutation".into()),
        };
        fs::write(&lock, contents)?;

        assert!(matches!(
            TomlProjectStateStore.inspect(&root(repository.path())?),
            Err(ProjectStateError::LockFormat { .. })
        ));
    }
    Ok(())
}

#[test]
fn orphan_lock_is_refused_without_guessing_config() -> Result<(), Box<dyn Error>> {
    let repository = repository()?;
    let (project, _, lock) = project_paths(repository.path());
    fs::create_dir(project)?;
    fs::write(lock, "generated but orphaned")?;

    let error = initialize_project(
        &GitRepositoryLocator,
        &TomlProjectStateStore,
        repository.path(),
    );

    assert!(matches!(error, Err(InitializeProjectError::OrphanLock)));
    Ok(())
}

#[test]
fn non_directory_and_non_regular_known_paths_are_refused() -> Result<(), Box<dyn Error>> {
    let non_directory_repository = repository()?;
    let (project, _, _) = project_paths(non_directory_repository.path());
    fs::write(&project, "collision")?;
    assert!(matches!(
        TomlProjectStateStore.inspect(&root(non_directory_repository.path())?),
        Err(ProjectStateError::ExpectedDirectory(_))
    ));

    let non_regular_repository = repository()?;
    let (project, config, _) = project_paths(non_regular_repository.path());
    fs::create_dir(&project)?;
    fs::create_dir(config)?;
    assert!(matches!(
        TomlProjectStateStore.inspect(&root(non_regular_repository.path())?),
        Err(ProjectStateError::ExpectedFile(_))
    ));
    Ok(())
}

#[cfg(unix)]
#[test]
fn symlinks_at_each_protected_path_are_refused() -> Result<(), Box<dyn Error>> {
    use std::os::unix::fs::symlink;

    let symlinked_directory_repository = repository()?;
    let outside = tempfile::tempdir()?;
    let (project, _, _) = project_paths(symlinked_directory_repository.path());
    symlink(outside.path(), &project)?;
    assert!(matches!(
        TomlProjectStateStore.inspect(&root(symlinked_directory_repository.path())?),
        Err(ProjectStateError::Symlink(_))
    ));

    for target in ["config.toml", "gitserious.lock"] {
        let repository = repository()?;
        let outside = tempfile::NamedTempFile::new()?;
        let (project, _, _) = project_paths(repository.path());
        fs::create_dir(&project)?;
        symlink(outside.path(), project.join(target))?;
        assert!(matches!(
            TomlProjectStateStore.inspect(&root(repository.path())?),
            Err(ProjectStateError::Symlink(_))
        ));
    }
    Ok(())
}

#[test]
fn direct_store_creation_refuses_existing_authored_config() -> Result<(), Box<dyn Error>> {
    let repository = repository()?;
    let (project, config, lock_path) = project_paths(repository.path());
    fs::create_dir(&project)?;
    fs::write(&config, "preserve")?;
    let config_model = ProjectConfig::default_channel()?;
    let lock = resolve_project_lock(&config_model)?;

    assert!(matches!(
        TomlProjectStateStore.initialize(&root(repository.path())?, &config_model, &lock),
        Err(ProjectStateError::Collision(_))
    ));
    assert_eq!(fs::read_to_string(config)?, "preserve");
    assert!(!lock_path.exists());
    Ok(())
}
