use std::error::Error;
use std::fmt::{self, Display, Formatter};
use std::fs::{self, OpenOptions};
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::str::FromStr;
use std::sync::atomic::{AtomicU64, Ordering};

use gitserious_app::{
    Fingerprint, FingerprintError, ProjectConfig, ProjectConfigError, ProjectLock,
    ProjectLockError, ProjectState, ProjectStateStore, RepositoryRoot, ResolvedCommitType,
    ResolvedTemplate, ResolvedTemplateError,
};
use gitserious_core::{
    CommitTypeId, IdentifierError, SchemaVersion, SchemaVersionError, TemplateId, TemplateVersion,
    TemplateVersionError,
};
use serde::{Deserialize, Serialize};

const LOCAL_STATE_DIRECTORY: &str = ".gitserious";
const LOCAL_IGNORE_FILE: &str = ".gitignore";
const LOCAL_IGNORE_CONTENTS: &str = "*\n";
const CONFIG_FILE: &str = "gitserious.toml";
const LOCK_FILE: &str = "gitserious.lock";
const GENERATED_LOCK_HEADER: &str = "# This file is generated by gitserious. Do not edit.\n";

static TEMPORARY_SEQUENCE: AtomicU64 = AtomicU64::new(0);

/// TOML adapter for repository-local gitserious project state.
#[derive(Clone, Copy, Debug, Default)]
pub struct TomlProjectStateStore;

impl ProjectStateStore for TomlProjectStateStore {
    type Error = ProjectStateError;

    fn inspect(&self, root: &RepositoryRoot) -> Result<ProjectState, Self::Error> {
        let paths = ProjectPaths::new(root);
        let config_exists = regular_file_exists(&paths.config)?;
        let lock_exists = regular_file_exists(&paths.lock)?;
        match (config_exists, lock_exists) {
            (false, false) => Ok(ProjectState::Absent),
            (true, false) => Ok(ProjectState::ConfigOnly(read_config(&paths.config)?)),
            (false, true) => Ok(ProjectState::LockOnly),
            (true, true) => Ok(ProjectState::Initialized {
                config: read_config(&paths.config)?,
                lock: read_lock(&paths.lock)?,
            }),
        }
    }

    fn ensure_local_state(&self, root: &RepositoryRoot) -> Result<(), Self::Error> {
        let paths = ProjectPaths::new(root);
        let created_directory = ensure_directory(&paths.local_state, true)?;
        match regular_file_exists(&paths.local_ignore) {
            Ok(true) => Ok(()),
            Ok(false) => {
                if let Err(error) =
                    write_new_file(&paths.local_ignore, LOCAL_IGNORE_CONTENTS.as_bytes())
                {
                    return rollback_directory_if_created(
                        &paths.local_state,
                        created_directory,
                        error,
                    );
                }
                Ok(())
            }
            Err(error) => {
                rollback_directory_if_created(&paths.local_state, created_directory, error)
            }
        }
    }

    fn initialize(
        &self,
        root: &RepositoryRoot,
        config: &ProjectConfig,
        lock: &ProjectLock,
    ) -> Result<(), Self::Error> {
        let config_contents = render_config(config)?;
        let lock_contents = render_lock(lock)?;
        let paths = ProjectPaths::new(root);

        if regular_file_exists(&paths.config)? {
            return Err(ProjectStateError::Collision(paths.config));
        }
        if regular_file_exists(&paths.lock)? {
            return Err(ProjectStateError::Collision(paths.lock));
        }

        write_new_file(&paths.config, config_contents.as_bytes())?;
        if let Err(error) = write_new_file(&paths.lock, lock_contents.as_bytes()) {
            return Err(rollback_file(&paths.config, error));
        }
        Ok(())
    }

    fn create_lock(&self, root: &RepositoryRoot, lock: &ProjectLock) -> Result<(), Self::Error> {
        let contents = render_lock(lock)?;
        let paths = ProjectPaths::new(root);
        write_new_file(&paths.lock, contents.as_bytes())
    }

    fn replace_lock(
        &self,
        root: &RepositoryRoot,
        current: &ProjectLock,
        replacement: &ProjectLock,
    ) -> Result<(), Self::Error> {
        let contents = render_lock(replacement)?;
        let paths = ProjectPaths::new(root);
        if !regular_file_exists(&paths.lock)? || read_lock(&paths.lock)? != *current {
            return Err(ProjectStateError::ConcurrentLockChange(paths.lock));
        }

        let temporary = write_temporary_lock(root.as_path(), contents.as_bytes())?;

        let observed = match read_lock(&paths.lock) {
            Ok(observed) => observed,
            Err(error) => return Err(rollback_file(&temporary, error)),
        };
        if observed != *current {
            return Err(rollback_file(
                &temporary,
                ProjectStateError::ConcurrentLockChange(paths.lock),
            ));
        }

        if let Err(source) = fs::rename(&temporary, &paths.lock) {
            return Err(rollback_file(
                &temporary,
                ProjectStateError::Io {
                    operation: "replace",
                    path: paths.lock,
                    source,
                },
            ));
        }
        Ok(())
    }
}

struct ProjectPaths {
    local_state: PathBuf,
    local_ignore: PathBuf,
    config: PathBuf,
    lock: PathBuf,
}

impl ProjectPaths {
    fn new(root: &RepositoryRoot) -> Self {
        let local_state = root.as_path().join(LOCAL_STATE_DIRECTORY);
        Self {
            local_ignore: local_state.join(LOCAL_IGNORE_FILE),
            config: root.as_path().join(CONFIG_FILE),
            lock: root.as_path().join(LOCK_FILE),
            local_state,
        }
    }
}

fn directory_exists(path: &Path) -> Result<bool, ProjectStateError> {
    match fs::symlink_metadata(path) {
        Ok(metadata) if metadata.file_type().is_symlink() => {
            Err(ProjectStateError::Symlink(path.to_path_buf()))
        }
        Ok(metadata) if metadata.is_dir() => Ok(true),
        Ok(_) => Err(ProjectStateError::ExpectedDirectory(path.to_path_buf())),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(false),
        Err(source) => Err(ProjectStateError::Io {
            operation: "inspect",
            path: path.to_path_buf(),
            source,
        }),
    }
}

fn regular_file_exists(path: &Path) -> Result<bool, ProjectStateError> {
    match fs::symlink_metadata(path) {
        Ok(metadata) if metadata.file_type().is_symlink() => {
            Err(ProjectStateError::Symlink(path.to_path_buf()))
        }
        Ok(metadata) if metadata.is_file() => Ok(true),
        Ok(_) => Err(ProjectStateError::ExpectedFile(path.to_path_buf())),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(false),
        Err(source) => Err(ProjectStateError::Io {
            operation: "inspect",
            path: path.to_path_buf(),
            source,
        }),
    }
}

fn ensure_directory(path: &Path, create: bool) -> Result<bool, ProjectStateError> {
    if directory_exists(path)? {
        return Ok(false);
    }
    if !create {
        return Err(ProjectStateError::ExpectedDirectory(path.to_path_buf()));
    }
    fs::create_dir(path).map_err(|source| ProjectStateError::Io {
        operation: "create",
        path: path.to_path_buf(),
        source,
    })?;
    Ok(true)
}

fn write_new_file(path: &Path, contents: &[u8]) -> Result<(), ProjectStateError> {
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)
        .map_err(|source| {
            if source.kind() == io::ErrorKind::AlreadyExists {
                ProjectStateError::Collision(path.to_path_buf())
            } else {
                ProjectStateError::Io {
                    operation: "create",
                    path: path.to_path_buf(),
                    source,
                }
            }
        })?;

    if let Err(source) = file.write_all(contents).and_then(|()| file.sync_all()) {
        return Err(rollback_file(
            path,
            ProjectStateError::Io {
                operation: "write",
                path: path.to_path_buf(),
                source,
            },
        ));
    }
    Ok(())
}

fn rollback_file(path: &Path, original: ProjectStateError) -> ProjectStateError {
    match fs::remove_file(path) {
        Ok(()) => original,
        Err(source) if source.kind() == io::ErrorKind::NotFound => original,
        Err(source) => ProjectStateError::Rollback {
            original: Box::new(original),
            path: path.to_path_buf(),
            source,
        },
    }
}

fn rollback_directory_if_created(
    path: &Path,
    created: bool,
    original: ProjectStateError,
) -> Result<(), ProjectStateError> {
    if !created {
        return Err(original);
    }
    match fs::remove_dir(path) {
        Ok(()) => Err(original),
        Err(source) => Err(ProjectStateError::Rollback {
            original: Box::new(original),
            path: path.to_path_buf(),
            source,
        }),
    }
}

fn write_temporary_lock(directory: &Path, contents: &[u8]) -> Result<PathBuf, ProjectStateError> {
    for _ in 0..100 {
        let sequence = TEMPORARY_SEQUENCE.fetch_add(1, Ordering::Relaxed);
        let path = directory.join(format!(
            ".{LOCK_FILE}.tmp.{}.{}",
            std::process::id(),
            sequence
        ));
        match write_new_file(&path, contents) {
            Ok(()) => return Ok(path),
            Err(ProjectStateError::Collision(_)) => {}
            Err(error) => return Err(error),
        }
    }
    Err(ProjectStateError::TemporaryFileUnavailable(
        directory.to_path_buf(),
    ))
}

fn read_config(path: &Path) -> Result<ProjectConfig, ProjectStateError> {
    let contents = read_utf8(path)?;
    let wire = toml::from_str::<ConfigWire>(&contents).map_err(|source| {
        ProjectStateError::ConfigFormat {
            path: path.to_path_buf(),
            source: Box::new(ConfigFormatError::Toml(source)),
        }
    })?;
    config_from_wire(wire).map_err(|source| ProjectStateError::ConfigFormat {
        path: path.to_path_buf(),
        source: Box::new(source),
    })
}

fn read_lock(path: &Path) -> Result<ProjectLock, ProjectStateError> {
    let contents = read_utf8(path)?;
    let wire =
        toml::from_str::<LockWire>(&contents).map_err(|source| ProjectStateError::LockFormat {
            path: path.to_path_buf(),
            source: Box::new(LockFormatError::Toml(source)),
        })?;
    lock_from_wire(wire).map_err(|source| ProjectStateError::LockFormat {
        path: path.to_path_buf(),
        source: Box::new(source),
    })
}

fn read_utf8(path: &Path) -> Result<String, ProjectStateError> {
    fs::read_to_string(path).map_err(|source| ProjectStateError::Io {
        operation: "read",
        path: path.to_path_buf(),
        source,
    })
}

fn render_config(config: &ProjectConfig) -> Result<String, ProjectStateError> {
    let wire = ConfigWire {
        config_version: config.version(),
        active_template: config.active_template().to_string(),
    };
    render_toml(&wire, ProjectArtifact::Config).map(ensure_line_ending)
}

fn render_lock(lock: &ProjectLock) -> Result<String, ProjectStateError> {
    let resolved = lock.resolved_template();
    let wire = LockWire {
        lock_version: lock.version(),
        config_fingerprint: lock.config_fingerprint().to_string(),
        template_reference: lock.template_reference().to_string(),
        resolved_template: ResolvedTemplateWire {
            id: resolved.id().to_string(),
            version: resolved.version().get(),
            fingerprint: resolved.fingerprint().to_string(),
            commit_types: resolved
                .commit_types()
                .iter()
                .map(|commit_type| ResolvedCommitTypeWire {
                    id: commit_type.id().to_string(),
                    schema_version: commit_type.schema_version().get(),
                    definition_fingerprint: commit_type.definition_fingerprint().to_string(),
                })
                .collect(),
        },
    };
    let rendered = render_toml(&wire, ProjectArtifact::Lock)?;
    Ok(format!(
        "{GENERATED_LOCK_HEADER}{}",
        ensure_line_ending(rendered)
    ))
}

fn render_toml<T>(value: &T, artifact: ProjectArtifact) -> Result<String, ProjectStateError>
where
    T: Serialize,
{
    toml::to_string(value).map_err(|source| ProjectStateError::Serialization {
        artifact,
        source: Box::new(source),
    })
}

fn ensure_line_ending(mut value: String) -> String {
    if !value.ends_with('\n') {
        value.push('\n');
    }
    value
}

fn config_from_wire(wire: ConfigWire) -> Result<ProjectConfig, ConfigFormatError> {
    let active_template =
        TemplateId::new(wire.active_template).map_err(ConfigFormatError::TemplateId)?;
    ProjectConfig::new(wire.config_version, active_template).map_err(ConfigFormatError::Config)
}

fn lock_from_wire(wire: LockWire) -> Result<ProjectLock, LockFormatError> {
    let config_fingerprint = Fingerprint::from_str(&wire.config_fingerprint)
        .map_err(LockFormatError::ConfigFingerprint)?;
    let template_reference =
        TemplateId::new(wire.template_reference).map_err(LockFormatError::TemplateReference)?;
    let id = TemplateId::new(wire.resolved_template.id).map_err(LockFormatError::TemplateId)?;
    let version = TemplateVersion::new(wire.resolved_template.version)
        .map_err(LockFormatError::TemplateVersion)?;
    let fingerprint = Fingerprint::from_str(&wire.resolved_template.fingerprint)
        .map_err(LockFormatError::TemplateFingerprint)?;

    let mut commit_types = Vec::with_capacity(wire.resolved_template.commit_types.len());
    for (index, commit_type) in wire.resolved_template.commit_types.into_iter().enumerate() {
        let id = CommitTypeId::new(commit_type.id)
            .map_err(|source| LockFormatError::CommitTypeId { index, source })?;
        let schema_version = SchemaVersion::new(commit_type.schema_version)
            .map_err(|source| LockFormatError::SchemaVersion { index, source })?;
        let definition_fingerprint = Fingerprint::from_str(&commit_type.definition_fingerprint)
            .map_err(|source| LockFormatError::DefinitionFingerprint { index, source })?;
        commit_types.push(ResolvedCommitType::new(
            id,
            schema_version,
            definition_fingerprint,
        ));
    }

    let resolved_template = ResolvedTemplate::new(id, version, fingerprint, commit_types)
        .map_err(LockFormatError::ResolvedTemplate)?;
    ProjectLock::new(
        wire.lock_version,
        config_fingerprint,
        template_reference,
        resolved_template,
    )
    .map_err(LockFormatError::Lock)
}

#[derive(Deserialize, Serialize)]
#[serde(rename_all = "kebab-case", deny_unknown_fields)]
struct ConfigWire {
    config_version: u16,
    active_template: String,
}

#[derive(Deserialize, Serialize)]
#[serde(rename_all = "kebab-case", deny_unknown_fields)]
struct LockWire {
    lock_version: u16,
    config_fingerprint: String,
    template_reference: String,
    resolved_template: ResolvedTemplateWire,
}

#[derive(Deserialize, Serialize)]
#[serde(rename_all = "kebab-case", deny_unknown_fields)]
struct ResolvedTemplateWire {
    id: String,
    version: u16,
    fingerprint: String,
    commit_types: Vec<ResolvedCommitTypeWire>,
}

#[derive(Deserialize, Serialize)]
#[serde(rename_all = "kebab-case", deny_unknown_fields)]
struct ResolvedCommitTypeWire {
    id: String,
    schema_version: u16,
    definition_fingerprint: String,
}

/// A repository-local project artifact being serialized.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProjectArtifact {
    /// Authored project configuration.
    Config,
    /// Generated resolved policy.
    Lock,
}

impl Display for ProjectArtifact {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::Config => CONFIG_FILE,
            Self::Lock => LOCK_FILE,
        })
    }
}

/// Failure to decode authored project configuration.
#[derive(Debug)]
pub enum ConfigFormatError {
    /// TOML syntax or shape is invalid.
    Toml(toml::de::Error),
    /// The active template reference is not a valid domain identifier.
    TemplateId(IdentifierError),
    /// The configuration version is unsupported.
    Config(ProjectConfigError),
}

impl Display for ConfigFormatError {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
        match self {
            Self::Toml(error) => Display::fmt(error, formatter),
            Self::TemplateId(error) => Display::fmt(error, formatter),
            Self::Config(error) => Display::fmt(error, formatter),
        }
    }
}

impl Error for ConfigFormatError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Toml(error) => Some(error),
            Self::TemplateId(error) => Some(error),
            Self::Config(error) => Some(error),
        }
    }
}

/// Failure to decode a generated project lock.
#[derive(Debug)]
pub enum LockFormatError {
    /// TOML syntax or shape is invalid.
    Toml(toml::de::Error),
    /// The config fingerprint is malformed.
    ConfigFingerprint(FingerprintError),
    /// The authored template reference is invalid.
    TemplateReference(IdentifierError),
    /// The resolved template identifier is invalid.
    TemplateId(IdentifierError),
    /// The resolved template version is invalid.
    TemplateVersion(TemplateVersionError),
    /// The resolved template fingerprint is malformed.
    TemplateFingerprint(FingerprintError),
    /// A commit-type identifier is invalid.
    CommitTypeId {
        /// The ordered lock entry index.
        index: usize,
        /// The rejected identifier error.
        source: IdentifierError,
    },
    /// A commit-type schema version is invalid.
    SchemaVersion {
        /// The ordered lock entry index.
        index: usize,
        /// The rejected version error.
        source: SchemaVersionError,
    },
    /// A commit-type definition fingerprint is malformed.
    DefinitionFingerprint {
        /// The ordered lock entry index.
        index: usize,
        /// The rejected fingerprint error.
        source: FingerprintError,
    },
    /// The resolved template violates structural invariants.
    ResolvedTemplate(ResolvedTemplateError),
    /// The lock format version is unsupported.
    Lock(ProjectLockError),
}

impl Display for LockFormatError {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
        match self {
            Self::Toml(error) => Display::fmt(error, formatter),
            Self::ConfigFingerprint(error)
            | Self::TemplateFingerprint(error)
            | Self::DefinitionFingerprint { source: error, .. } => Display::fmt(error, formatter),
            Self::TemplateReference(error)
            | Self::TemplateId(error)
            | Self::CommitTypeId { source: error, .. } => Display::fmt(error, formatter),
            Self::TemplateVersion(error) => Display::fmt(error, formatter),
            Self::SchemaVersion { source, .. } => Display::fmt(source, formatter),
            Self::ResolvedTemplate(error) => Display::fmt(error, formatter),
            Self::Lock(error) => Display::fmt(error, formatter),
        }
    }
}

impl Error for LockFormatError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Toml(error) => Some(error),
            Self::ConfigFingerprint(error)
            | Self::TemplateFingerprint(error)
            | Self::DefinitionFingerprint { source: error, .. } => Some(error),
            Self::TemplateReference(error)
            | Self::TemplateId(error)
            | Self::CommitTypeId { source: error, .. } => Some(error),
            Self::TemplateVersion(error) => Some(error),
            Self::SchemaVersion { source, .. } => Some(source),
            Self::ResolvedTemplate(error) => Some(error),
            Self::Lock(error) => Some(error),
        }
    }
}

/// Failure to inspect or mutate repository-local project state safely.
#[derive(Debug)]
pub enum ProjectStateError {
    /// An operating-system filesystem operation failed.
    Io {
        /// The attempted operation.
        operation: &'static str,
        /// The affected path.
        path: PathBuf,
        /// The underlying I/O error.
        source: io::Error,
    },
    /// A protected project path is a symbolic link.
    Symlink(PathBuf),
    /// The project directory path exists but is not a directory.
    ExpectedDirectory(PathBuf),
    /// A known project file path exists but is not a regular file.
    ExpectedFile(PathBuf),
    /// Exclusive creation encountered an existing target.
    Collision(PathBuf),
    /// Authored configuration could not be decoded safely.
    ConfigFormat {
        /// The invalid config path.
        path: PathBuf,
        /// The typed format failure.
        source: Box<ConfigFormatError>,
    },
    /// Generated lock state could not be decoded safely.
    LockFormat {
        /// The invalid lock path.
        path: PathBuf,
        /// The typed format failure.
        source: Box<LockFormatError>,
    },
    /// A domain value could not be serialized to TOML.
    Serialization {
        /// The artifact being serialized.
        artifact: ProjectArtifact,
        /// The TOML serialization failure.
        source: Box<toml::ser::Error>,
    },
    /// The lock changed between inspection and replacement.
    ConcurrentLockChange(PathBuf),
    /// No exclusive temporary lock path could be reserved.
    TemporaryFileUnavailable(PathBuf),
    /// Cleanup of an invocation-created artifact failed.
    Rollback {
        /// The original operation failure.
        original: Box<ProjectStateError>,
        /// The artifact that could not be removed.
        path: PathBuf,
        /// The cleanup failure.
        source: io::Error,
    },
}

impl Display for ProjectStateError {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io {
                operation,
                path,
                source,
            } => write!(
                formatter,
                "could not {operation} {}: {source}",
                path.display()
            ),
            Self::Symlink(path) => write!(
                formatter,
                "refusing symbolic link at protected project path {}",
                path.display()
            ),
            Self::ExpectedDirectory(path) => {
                write!(formatter, "expected a directory at {}", path.display())
            }
            Self::ExpectedFile(path) => {
                write!(formatter, "expected a regular file at {}", path.display())
            }
            Self::Collision(path) => write!(
                formatter,
                "refusing to overwrite existing project state at {}",
                path.display()
            ),
            Self::ConfigFormat { path, source } => write!(
                formatter,
                "invalid authored configuration {}: {source}",
                path.display()
            ),
            Self::LockFormat { path, source } => write!(
                formatter,
                "invalid generated lock {}: {source}",
                path.display()
            ),
            Self::Serialization { artifact, source } => {
                write!(formatter, "could not serialize {artifact}: {source}")
            }
            Self::ConcurrentLockChange(path) => write!(
                formatter,
                "generated lock changed concurrently at {}; retry initialization",
                path.display()
            ),
            Self::TemporaryFileUnavailable(path) => write!(
                formatter,
                "could not reserve a temporary lock file in {}; retry initialization",
                path.display()
            ),
            Self::Rollback {
                original,
                path,
                source,
            } => write!(
                formatter,
                "{original}; cleanup also failed for {}: {source}",
                path.display()
            ),
        }
    }
}

impl Error for ProjectStateError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Io { source, .. } => Some(source),
            Self::ConfigFormat { source, .. } => Some(source.as_ref()),
            Self::LockFormat { source, .. } => Some(source.as_ref()),
            Self::Serialization { source, .. } => Some(source.as_ref()),
            Self::Rollback { original, .. } => Some(original.as_ref()),
            Self::Symlink(_)
            | Self::ExpectedDirectory(_)
            | Self::ExpectedFile(_)
            | Self::Collision(_)
            | Self::ConcurrentLockChange(_)
            | Self::TemporaryFileUnavailable(_) => None,
        }
    }
}
