use std::error::Error;
use std::fmt::{self, Display, Formatter};
use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::str::FromStr;

use gitserious_app::{
    Fingerprint, ProjectConfig, ProjectLock, ProjectState, ProjectStateStore, RepositoryRoot,
};
use gitserious_core::TaxonomyId;
use serde::{Deserialize, Serialize};
use tempfile::NamedTempFile;

use crate::taxonomy_wire::{TaxonomyWire, legacy_shape, taxonomy_from_wire, taxonomy_to_wire};

const CONFIG_FILE: &str = "gitserious.toml";
const LOCK_FILE: &str = "gitserious.lock";
const LOCAL_STATE_DIRECTORY: &str = ".gitserious";
const LOCAL_IGNORE_CONTENTS: &str = "*\n";
const LOCK_HEADER: &str = "# This file is generated by gitserious. Do not edit.\n";

/// Strict TOML adapter for taxonomy-first project configuration and portable locks.
#[derive(Clone, Copy, Debug, Default)]
pub struct TomlProjectStateStore;

impl ProjectStateStore for TomlProjectStateStore {
    type Error = ProjectStateError;

    fn inspect(&self, root: &RepositoryRoot) -> Result<ProjectState, Self::Error> {
        let config = root.as_path().join(CONFIG_FILE);
        let lock = root.as_path().join(LOCK_FILE);
        let config_exists = regular_file_exists(&config)?;
        let lock_exists = regular_file_exists(&lock)?;
        match (config_exists, lock_exists) {
            (false, false) => Ok(ProjectState::Absent),
            (true, false) => Ok(ProjectState::ConfigOnly(read_config(&config)?)),
            (false, true) => Ok(ProjectState::LockOnly),
            (true, true) => Ok(ProjectState::Initialized {
                config: read_config(&config)?,
                lock: read_lock(&lock)?,
            }),
        }
    }

    fn ensure_local_state(&self, root: &RepositoryRoot) -> Result<(), Self::Error> {
        let directory = root.as_path().join(LOCAL_STATE_DIRECTORY);
        fs::create_dir_all(&directory).map_err(|source| ProjectStateError::Io {
            operation: "create directory",
            path: directory.clone(),
            source,
        })?;
        let ignore = directory.join(".gitignore");
        if !regular_file_exists(&ignore)? {
            fs::write(&ignore, LOCAL_IGNORE_CONTENTS).map_err(|source| ProjectStateError::Io {
                operation: "write",
                path: ignore,
                source,
            })?;
        }
        Ok(())
    }

    fn initialize(
        &self,
        root: &RepositoryRoot,
        config: &ProjectConfig,
        lock: &ProjectLock,
    ) -> Result<(), Self::Error> {
        let config_path = root.as_path().join(CONFIG_FILE);
        let lock_path = root.as_path().join(LOCK_FILE);
        if regular_file_exists(&config_path)? {
            return Err(ProjectStateError::Collision(config_path));
        }
        if regular_file_exists(&lock_path)? {
            return Err(ProjectStateError::Collision(lock_path));
        }
        let config_temp = prepare(root.as_path(), render_config(config)?.as_bytes())?;
        let lock_temp = prepare(root.as_path(), render_lock(lock)?.as_bytes())?;
        persist_new(config_temp, &config_path)?;
        if let Err(error) = persist_new(lock_temp, &lock_path) {
            let _ = fs::remove_file(&config_path);
            return Err(error);
        }
        Ok(())
    }

    fn create_lock(&self, root: &RepositoryRoot, lock: &ProjectLock) -> Result<(), Self::Error> {
        let path = root.as_path().join(LOCK_FILE);
        let temporary = prepare(root.as_path(), render_lock(lock)?.as_bytes())?;
        persist_new(temporary, &path)
    }

    fn replace_lock(
        &self,
        root: &RepositoryRoot,
        current: &ProjectLock,
        replacement: &ProjectLock,
    ) -> Result<(), Self::Error> {
        let path = root.as_path().join(LOCK_FILE);
        if read_lock(&path)? != *current {
            return Err(ProjectStateError::ConcurrentChange(path));
        }
        let temporary = prepare(root.as_path(), render_lock(replacement)?.as_bytes())?;
        if read_lock(&path)? != *current {
            return Err(ProjectStateError::ConcurrentChange(path));
        }
        persist_replace(temporary, &path)
    }

    fn compare_and_swap(
        &self,
        root: &RepositoryRoot,
        current_config: &ProjectConfig,
        current_lock: &ProjectLock,
        replacement_config: &ProjectConfig,
        replacement_lock: &ProjectLock,
    ) -> Result<(), Self::Error> {
        let config_path = root.as_path().join(CONFIG_FILE);
        let lock_path = root.as_path().join(LOCK_FILE);
        ensure_expected(&config_path, current_config, &lock_path, current_lock)?;
        let config_temp = prepare(
            root.as_path(),
            render_config(replacement_config)?.as_bytes(),
        )?;
        let lock_temp = prepare(root.as_path(), render_lock(replacement_lock)?.as_bytes())?;
        let lock_backup = prepare(root.as_path(), render_lock(current_lock)?.as_bytes())?;
        ensure_expected(&config_path, current_config, &lock_path, current_lock)?;
        persist_replace(lock_temp, &lock_path)?;
        if let Err(error) = persist_replace(config_temp, &config_path) {
            if let Err(rollback) = persist_replace(lock_backup, &lock_path) {
                return Err(ProjectStateError::Rollback {
                    original: Box::new(error),
                    rollback: Box::new(rollback),
                });
            }
            return Err(error);
        }
        Ok(())
    }
}

fn ensure_expected(
    config_path: &Path,
    config: &ProjectConfig,
    lock_path: &Path,
    lock: &ProjectLock,
) -> Result<(), ProjectStateError> {
    if read_config(config_path)? != *config || read_lock(lock_path)? != *lock {
        return Err(ProjectStateError::ConcurrentChange(
            config_path.to_path_buf(),
        ));
    }
    Ok(())
}

fn regular_file_exists(path: &Path) -> Result<bool, ProjectStateError> {
    match fs::symlink_metadata(path) {
        Ok(metadata) if metadata.file_type().is_symlink() || !metadata.is_file() => {
            Err(ProjectStateError::UnsafePath(path.to_path_buf()))
        }
        Ok(_) => Ok(true),
        Err(source) if source.kind() == io::ErrorKind::NotFound => Ok(false),
        Err(source) => Err(ProjectStateError::Io {
            operation: "inspect",
            path: path.to_path_buf(),
            source,
        }),
    }
}

fn read_text(path: &Path) -> Result<String, ProjectStateError> {
    fs::read_to_string(path).map_err(|source| ProjectStateError::Io {
        operation: "read",
        path: path.to_path_buf(),
        source,
    })
}

fn read_config(path: &Path) -> Result<ProjectConfig, ProjectStateError> {
    let contents = read_text(path)?;
    if legacy_shape(&contents) {
        return Err(ProjectStateError::LegacyFormat(path.to_path_buf()));
    }
    let wire: ProjectConfigWire =
        toml::from_str(&contents).map_err(|source| ProjectStateError::Format {
            path: path.to_path_buf(),
            message: source.to_string(),
        })?;
    let default = wire
        .default_taxonomy
        .map(TaxonomyId::new)
        .transpose()
        .map_err(|error| ProjectStateError::Format {
            path: path.to_path_buf(),
            message: error.to_string(),
        })?;
    let available = wire
        .available_taxonomies
        .map(|ids| {
            ids.into_iter()
                .map(TaxonomyId::new)
                .collect::<Result<Vec<_>, _>>()
        })
        .transpose()
        .map_err(|error| ProjectStateError::Format {
            path: path.to_path_buf(),
            message: error.to_string(),
        })?;
    ProjectConfig::new(wire.config_version, default, available).map_err(|error| {
        ProjectStateError::Format {
            path: path.to_path_buf(),
            message: error.to_string(),
        }
    })
}

fn read_lock(path: &Path) -> Result<ProjectLock, ProjectStateError> {
    let contents = read_text(path)?;
    if legacy_shape(&contents) || contents.contains("resolved-template") {
        return Err(ProjectStateError::LegacyFormat(path.to_path_buf()));
    }
    let wire: LockWire = toml::from_str(&contents).map_err(|source| ProjectStateError::Format {
        path: path.to_path_buf(),
        message: source.to_string(),
    })?;
    let fingerprint = Fingerprint::from_str(&wire.config_fingerprint).map_err(|error| {
        ProjectStateError::Format {
            path: path.to_path_buf(),
            message: error.to_string(),
        }
    })?;
    let default =
        TaxonomyId::new(wire.default_taxonomy).map_err(|error| ProjectStateError::Format {
            path: path.to_path_buf(),
            message: error.to_string(),
        })?;
    let taxonomies = wire
        .taxonomies
        .into_iter()
        .enumerate()
        .map(|(index, value)| taxonomy_from_wire(value, &format!("taxonomies[{index}]")))
        .collect::<Result<Vec<_>, _>>()
        .map_err(|message| ProjectStateError::Format {
            path: path.to_path_buf(),
            message,
        })?;
    ProjectLock::new(wire.lock_version, fingerprint, default, taxonomies).map_err(|error| {
        ProjectStateError::Format {
            path: path.to_path_buf(),
            message: error.to_string(),
        }
    })
}

fn render_config(config: &ProjectConfig) -> Result<String, ProjectStateError> {
    toml::to_string_pretty(&ProjectConfigWire {
        config_version: config.version(),
        default_taxonomy: config.default_taxonomy().map(ToString::to_string),
        available_taxonomies: config
            .available_taxonomies()
            .map(|ids| ids.iter().map(ToString::to_string).collect()),
    })
    .map_err(|source| ProjectStateError::Serialize(source.to_string()))
}

fn render_lock(lock: &ProjectLock) -> Result<String, ProjectStateError> {
    let body = toml::to_string_pretty(&LockWire {
        lock_version: lock.version(),
        config_fingerprint: lock.config_fingerprint().to_string(),
        default_taxonomy: lock.default_taxonomy().to_string(),
        taxonomies: lock.taxonomies().iter().map(taxonomy_to_wire).collect(),
    })
    .map_err(|source| ProjectStateError::Serialize(source.to_string()))?;
    Ok(format!("{LOCK_HEADER}{body}"))
}

fn prepare(directory: &Path, contents: &[u8]) -> Result<NamedTempFile, ProjectStateError> {
    let mut file = NamedTempFile::new_in(directory).map_err(|source| ProjectStateError::Io {
        operation: "create temporary file",
        path: directory.to_path_buf(),
        source,
    })?;
    file.write_all(contents)
        .and_then(|()| file.as_file().sync_all())
        .map_err(|source| ProjectStateError::Io {
            operation: "write temporary file",
            path: file.path().to_path_buf(),
            source,
        })?;
    Ok(file)
}

fn persist_new(file: NamedTempFile, path: &Path) -> Result<(), ProjectStateError> {
    file.persist_noclobber(path).map(|_| ()).map_err(|error| {
        if error.error.kind() == io::ErrorKind::AlreadyExists {
            ProjectStateError::Collision(path.to_path_buf())
        } else {
            ProjectStateError::Io {
                operation: "create",
                path: path.to_path_buf(),
                source: error.error,
            }
        }
    })
}

fn persist_replace(file: NamedTempFile, path: &Path) -> Result<(), ProjectStateError> {
    file.persist(path)
        .map(|_| ())
        .map_err(|error| ProjectStateError::Io {
            operation: "replace",
            path: path.to_path_buf(),
            source: error.error,
        })
}

#[derive(Deserialize, Serialize)]
#[serde(rename_all = "kebab-case", deny_unknown_fields)]
struct ProjectConfigWire {
    config_version: u16,
    #[serde(skip_serializing_if = "Option::is_none")]
    default_taxonomy: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    available_taxonomies: Option<Vec<String>>,
}

#[derive(Deserialize, Serialize)]
#[serde(rename_all = "kebab-case", deny_unknown_fields)]
struct LockWire {
    lock_version: u16,
    config_fingerprint: String,
    default_taxonomy: String,
    taxonomies: Vec<TaxonomyWire>,
}

/// Project persistence failure.
#[derive(Debug)]
pub enum ProjectStateError {
    LegacyFormat(PathBuf),
    Format {
        path: PathBuf,
        message: String,
    },
    Serialize(String),
    Collision(PathBuf),
    ConcurrentChange(PathBuf),
    UnsafePath(PathBuf),
    Io {
        operation: &'static str,
        path: PathBuf,
        source: io::Error,
    },
    Rollback {
        original: Box<ProjectStateError>,
        rollback: Box<ProjectStateError>,
    },
}

impl Display for ProjectStateError {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
        match self {
            Self::LegacyFormat(path) => write!(
                formatter,
                "{} uses the superseded pre-release template/typeset format; back it up and recreate it with taxonomy-first gitserious config",
                path.display()
            ),
            Self::Format { path, message } => write!(
                formatter,
                "invalid project artifact {}: {message}",
                path.display()
            ),
            Self::Serialize(message) => {
                write!(formatter, "could not serialize project policy: {message}")
            }
            Self::Collision(path) => write!(
                formatter,
                "refusing to overwrite existing {}",
                path.display()
            ),
            Self::ConcurrentChange(path) => write!(
                formatter,
                "project policy changed while editing: {}",
                path.display()
            ),
            Self::UnsafePath(path) => write!(
                formatter,
                "project policy path is not a regular file: {}",
                path.display()
            ),
            Self::Io {
                operation,
                path,
                source,
            } => write!(
                formatter,
                "could not {operation} {}: {source}",
                path.display()
            ),
            Self::Rollback { original, rollback } => {
                write!(formatter, "{original}; rollback also failed: {rollback}")
            }
        }
    }
}

impl Error for ProjectStateError {}
