use std::error::Error;
use std::fs;
use std::path::Path;
use std::process::{Command, Output};

use tempfile::TempDir;

fn binary() -> &'static str {
    env!("CARGO_BIN_EXE_gitserious")
}

fn repository() -> Result<TempDir, Box<dyn Error>> {
    let directory = tempfile::tempdir()?;
    let status = Command::new("git")
        .args(["init", "-q"])
        .current_dir(directory.path())
        .status()?;
    if !status.success() {
        return Err(format!("git init failed with {status}").into());
    }
    Ok(directory)
}

fn run(directory: &Path, arguments: &[&str]) -> Result<Output, Box<dyn Error>> {
    Ok(Command::new(binary())
        .args(arguments)
        .current_dir(directory)
        .output()?)
}

fn git(directory: &Path, arguments: &[&str]) -> Result<Output, Box<dyn Error>> {
    let output = Command::new("git")
        .args(arguments)
        .current_dir(directory)
        .output()?;
    if output.status.success() {
        Ok(output)
    } else {
        Err(format!(
            "git {} failed: {}{}",
            arguments.join(" "),
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        )
        .into())
    }
}

fn stdout(output: &Output) -> String {
    String::from_utf8_lossy(&output.stdout).into_owned()
}

fn stderr(output: &Output) -> String {
    String::from_utf8_lossy(&output.stderr).into_owned()
}

#[test]
fn nested_first_run_creates_exact_version_control_artifacts() -> Result<(), Box<dyn Error>> {
    let repository = repository()?;
    let nested = repository.path().join("one/two");
    fs::create_dir_all(&nested)?;

    let output = run(&nested, &["init"])?;
    let git_root =
        String::from_utf8(git(repository.path(), &["rev-parse", "--show-toplevel"])?.stdout)?;

    assert!(output.status.success(), "{}", stderr(&output));
    assert!(stdout(&output).contains(&format!("Initialized gitserious in {}", git_root.trim())));
    assert!(stdout(&output).contains("(default -> conventional@1)."));
    assert!(stderr(&output).is_empty());
    assert_eq!(
        fs::read_to_string(repository.path().join("gitserious.toml"))?,
        "config-version = 1\nactive-template = \"default\"\n\
         taxonomies = []\ntypesets = []\ntemplates = []\n"
    );
    let lock = fs::read_to_string(repository.path().join("gitserious.lock"))?;
    assert!(lock.starts_with("# This file is generated by gitserious. Do not edit.\n"));
    assert_eq!(
        lock.matches("[[resolved-template.commit-types]]").count(),
        11
    );
    assert_eq!(
        fs::read_to_string(repository.path().join(".gitserious/.gitignore"))?,
        "*\n"
    );
    fs::create_dir(repository.path().join(".gitserious/cache"))?;
    fs::write(
        repository.path().join(".gitserious/cache/state"),
        "ignored\n",
    )?;
    git(
        repository.path(),
        &["check-ignore", "-q", ".gitserious/cache/state"],
    )?;
    Ok(())
}

#[test]
fn linked_worktree_initializes_only_its_own_root() -> Result<(), Box<dyn Error>> {
    let primary = repository()?;
    git(
        primary.path(),
        &[
            "-c",
            "user.name=Git Serious",
            "-c",
            "user.email=gitserious@example.com",
            "commit",
            "--allow-empty",
            "-m",
            "initial",
        ],
    )?;
    let worktrees = tempfile::tempdir()?;
    let linked = worktrees.path().join("linked");
    git(
        primary.path(),
        &[
            "worktree",
            "add",
            "--detach",
            linked.to_string_lossy().as_ref(),
        ],
    )?;
    let nested = linked.join("one/two");
    fs::create_dir_all(&nested)?;

    let output = run(&nested, &["init"])?;

    assert!(output.status.success(), "{}", stderr(&output));
    assert!(linked.join("gitserious.toml").is_file());
    assert!(linked.join("gitserious.lock").is_file());
    assert!(linked.join(".gitserious/.gitignore").is_file());
    assert!(!primary.path().join("gitserious.toml").exists());
    assert!(!primary.path().join("gitserious.lock").exists());
    assert!(!primary.path().join(".gitserious").exists());
    Ok(())
}

#[test]
fn repeat_missing_lock_and_stale_lock_report_distinct_outcomes() -> Result<(), Box<dyn Error>> {
    let repository = repository()?;
    let config = repository.path().join("gitserious.toml");
    let lock = repository.path().join("gitserious.lock");
    assert!(run(repository.path(), &["init"])?.status.success());
    let authored = fs::read(&config)?;
    let current = fs::read_to_string(&lock)?;

    let repeated = run(repository.path(), &["init"])?;
    assert!(repeated.status.success());
    assert!(stdout(&repeated).contains("already initialized"));
    assert_eq!(fs::read(&config)?, authored);
    assert_eq!(fs::read_to_string(&lock)?, current);

    fs::remove_file(&lock)?;
    let missing = run(repository.path(), &["init"])?;
    assert!(missing.status.success());
    assert!(stdout(&missing).contains("Created missing lock"));
    assert_eq!(fs::read(&config)?, authored);
    assert_eq!(fs::read_to_string(&lock)?, current);

    let stale = current.replace(
        "config-fingerprint = \"sha256:e",
        "config-fingerprint = \"sha256:a",
    );
    fs::write(&lock, stale)?;
    let refreshed = run(repository.path(), &["init"])?;
    assert!(refreshed.status.success());
    assert!(stdout(&refreshed).contains("Refreshed "));
    assert_eq!(fs::read(&config)?, authored);
    assert_eq!(fs::read_to_string(&lock)?, current);
    Ok(())
}

#[test]
fn local_state_contents_are_not_read_as_project_policy() -> Result<(), Box<dyn Error>> {
    let repository = repository()?;
    let local = repository.path().join(".gitserious");
    fs::create_dir(&local)?;
    fs::write(local.join("config.toml"), "not project policy\n")?;
    fs::write(local.join("gitserious.lock"), "not project policy\n")?;

    let output = run(repository.path(), &["init"])?;

    assert!(output.status.success(), "{}", stderr(&output));
    assert!(repository.path().join("gitserious.toml").is_file());
    assert!(repository.path().join("gitserious.lock").is_file());
    assert_eq!(
        fs::read_to_string(local.join("config.toml"))?,
        "not project policy\n"
    );
    assert_eq!(
        fs::read_to_string(local.join("gitserious.lock"))?,
        "not project policy\n"
    );
    Ok(())
}

#[test]
fn non_repository_fails_without_creating_project_state() -> Result<(), Box<dyn Error>> {
    let directory = tempfile::tempdir()?;

    let output = run(directory.path(), &["init"])?;

    assert_eq!(output.status.code(), Some(1));
    assert!(stdout(&output).is_empty());
    assert!(stderr(&output).contains("not inside a Git worktree"));
    assert!(!directory.path().join(".gitserious").exists());
    assert!(!directory.path().join("gitserious.toml").exists());
    assert!(!directory.path().join("gitserious.lock").exists());
    Ok(())
}

#[test]
fn unavailable_git_fails_before_creating_project_state() -> Result<(), Box<dyn Error>> {
    let directory = tempfile::tempdir()?;

    let output = Command::new(binary())
        .arg("init")
        .env("PATH", "")
        .current_dir(directory.path())
        .output()?;

    assert_eq!(output.status.code(), Some(1));
    assert!(stdout(&output).is_empty());
    assert_eq!(stderr(&output), "error: could not execute git\n");
    assert!(!directory.path().join(".gitserious").exists());
    assert!(!directory.path().join("gitserious.toml").exists());
    assert!(!directory.path().join("gitserious.lock").exists());
    Ok(())
}

#[test]
fn help_version_and_usage_exit_codes_match_the_public_contract() -> Result<(), Box<dyn Error>> {
    let directory = tempfile::tempdir()?;

    for arguments in [&["--help"][..], &["--version"][..]] {
        let output = run(directory.path(), arguments)?;
        assert!(output.status.success(), "{}", stderr(&output));
        assert!(!stdout(&output).is_empty());
        assert!(stderr(&output).is_empty());
    }
    for arguments in [&[][..], &["unknown"][..], &["init", "extra"][..]] {
        let output = run(directory.path(), arguments)?;
        assert_eq!(output.status.code(), Some(2));
        assert!(stdout(&output).is_empty());
        assert!(stderr(&output).contains("Usage:"));
    }
    Ok(())
}
